config/routes.rb
YardRecords::Application.routes.draw do
  railsyard_authentication_devise_for :users

  root to: "pages#home"
  get "/contact-us" => "pages#contact", :as => :contact
  get "/about-us" => "pages#about", :as => :about

  resources :releases, only: [:index, :show] do
    get 'type/:type' => 'releases#type', :on => :collection, :as => :type
  end
  resources :artists, only: [:index] do
    get ':pretty_url' => "artists#show", :on => :collection, :as => :show
  end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_image_gallery :photos
  accepts_nested_attributes_for :photos
  attr_accessible :homepage_url, :country, :biography, :name, :photos_attributes, :pretty_url

  has_and_belongs_to_many :releases

  before_save { |artist| artist.pretty_url = artist.name.urlify }
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name, :position, :parent, :parent_id
  belongs_to :parent, class_name: "Genre"

  scope :roots, where(parent_id: nil)
  default_scope order(:position)

  def children
    Genre.where(parent_id: self)
  end

  def parent
    Genre.find parent_id if parent_id
  end

  def parents(genres=[self])
    root = genres.first
    if root.parent.present?
      parents([root.parent] + genres)
    else
      genres
    end
  end
end

app/models/release.rb
class Release < ActiveRecord::Base
  has_image :artwork
  accepts_nested_attributes_for :artwork

  belongs_to :release_type
  belongs_to :genre
  attr_accessible :barcode, :name, :published, :release_date, :tracklist, :artwork_attributes, :artwork_artist, :genre_id, :release_type_id, :artist_ids

  has_and_belongs_to_many :artists

  default_scope where(published: true).order("created_at DESC")

  def genres
    genre.parents.map(&:name).join ', '
  end
end

app/models/release_type.rb
class ReleaseType < ActiveRecord::Base
  attr_accessible :name, :pretty_url
  has_many :releases

  default_scope :order => :name

  before_save { |type| type.pretty_url = type.name.urlify }
end

app/models/settings.rb
class Settings < ActiveRecord::Base
  attr_accessible :site_name, :home_banner_text, :home_text, :about_text, :contact_text, :contact_address, :contact_phone, :contact_fax, :contact_email, :contact_latitude, :contact_longitude

  def self.instance
    if self.count.zero?
      self.create
    end
    self.first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :get_settings

  protected
  def get_settings
    @settings = Settings.instance
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  layout "soundrock"

  def index
    @title = "All artists"
    @artists = Artist.all
  end

  def show
    @artist = Artist.find_by_pretty_url params[:pretty_url]
    raise ActionController::RoutingError.new('Not Found') unless @artist
    @title = @artist.name
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "soundrock"

  def home
    @title = "Home"
    @latest_releases = Release.limit(2)
  end

  def about
    @title = "About Us"
  end

  def contact
    @title = "Contact Us"
  end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  layout "soundrock"

  def index
    @title = "All releases"
    @items = Release.all
  end

  def type
    if params[:type]
      type = ReleaseType.find_by_pretty_url(params[:type])
      @title = type.name
      @items = type.releases
      render :index
    else
      render :action => :index
    end
  end

  def show
    @release = Release.find params[:id]
    @title = @release.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def artists_links(artists)
    if artists.length == 1
      a = artists.first
      link_to a.name, show_artists_path(pretty_url: a.pretty_url)
    else
      link_to "Various artists", '#'
    end
  end

end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/artists/index.html.erb
<% content_for :banner do %>
    <div id="sub-banner">
    	<div class="in">
        	<a href="#"><img src="/assets/soundrock/sub-banner1.jpg" alt="" /></a>
        </div>
    </div>
<% end %>

   <div id="content-sec">
    	<div class="inner">
        	<!-- Columns Section Start -->
            <div class="columns-sec twocol">
            	<!-- Column Three Start -->
                <div class="col3">
                	<div class="news">
                    	<h1 class="heading colr">Our artists</h1>
                        <ul class="late-news">
                          <% @artists.each do |artist| %>
                            <% featured = artist.photos.first %>
                            <li>
                            	<div class="thumb">
                                	<a href="<%= show_artists_path(pretty_url: artist.pretty_url) %>"><%= image_tag featured.image.thumb('210x210#').url if featured %></a>
                                </div>
                                <div class="desc">
                                  <h3><%= link_to artist.name, show_artists_path(pretty_url: artist.pretty_url), :class => :colr %></h3>
                                  <p><%= raw artist.biography %></p>
                                  <%= link_to "Continue Reading", show_artists_path(pretty_url: artist.pretty_url), :class => :readmore %>
                                </div>
                            </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <!-- Column One End -->
                <!-- Column One Start -->
                <div class="col1 hidemobile">
                    <!-- Facebook Start -->
                    <div class="widget facebook">
                        <a href="#"><img src="/assets/soundrock/facebook.jpg" alt="" /></a>
                    </div>
                    <!-- Facebook End -->
                    <!-- Newsletter Start -->
                    <div class="widget newsletter noback">
                    	<h1 class="heading colr">Weekly Newsletter</h1>
                        <input type="text" value="Enter your valid email address" />
                        <button>SUBMIT</button>
                    </div>
                    <!-- Newsletter End -->
                    <!-- Advertisment Start -->
                    <div class="widget advert">
                        <a href="#"><img src="/assets/soundrock/advert2.jpg" alt="" /></a>
                        <span>Advertising</span>
                    </div>
                    <!-- Advertisment End -->
                </div>
                <!-- Column One End -->
            </div>
            <!-- Columns Section End -->
        </div>
    </div>

app/views/artists/show.html.erb
<% content_for :banner do %>
    <div id="sub-banner">
    	<div class="in">
        	<a href="#"><img src="/assets/soundrock/sub-banner4.jpg" alt="" /></a>
        </div>
    </div>
<% end %>

    <div id="content-sec">
    	<div class="inner">
        	<!-- Columns Section Start -->
            <div class="columns-sec twocol">
            	<!-- Column Three Start -->
                <div class="col3">
                	<div class="blog">
                    	<h1 class="heading colr"><%= @artist.name %></h1>
                        <!-- Post Detail Start -->
                        <div class="post-detail">
                        	<div class="thumb">
                            <%= image_tag @artist.photos.first.image.thumb('680x270#').url if @artist.photos.first %>
                          </div>
                          <div class="desc">
                            <div class="post-opts">
                              <p>From <%= @artist.country %></p>
                              <p>Website: <%= link_to @artist.homepage_url, @artist.homepage_url %></p>
                            </div>
                            <%= raw @artist.biography %>
                          </div>
                        </div>
                        <div class="clear"></div>
                        <!-- Post Detail End -->
                    </div>
                </div>
                <!-- Column One End -->
                <!-- Column One Start -->
                <div class="col1 hidemobile">
                    <!-- Other Albums Start -->
                    <div class="widget albums-widget noback">
                    	<h1 class="heading colr">Albums</h1>
                        <ul>
                          <% @artist.releases.each do |release| %>
                        	<li>
                            	<a href="<%= release_path release %>" class="thumb"><%= image_tag release.artwork.image.thumb('120x104#').url if release.artwork %></a>
                                <div class="desc">
                                	<h4><%= link_to release.name, release_path(release) %></h4>
                                  <p class="date">Release: <%= release.release_date %></p>
                                  <%= link_to "Details", release_path(release) %>
                                </div>
                            </li>
                            <% end %>
                        </ul>
                    </div>
                    <!-- Other Albums End -->
                </div>
                <!-- Column One End -->
            </div>
            <!-- Columns Section End -->
        </div>
    </div>

app/views/layouts/soundrock.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<title><%= @settings.site_name %> <%= " :: #{@title}" if @title %></title>
<meta name="description" content="A made-up site to show Railsyard-backend features">
<meta name="author" content="Team Cantiere Creativo">
<!--// Mobile Metas //-->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!--// Stylesheets //-->
<%= stylesheet_link_tag    "application", :media => "all" %>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--// Favicons //-->
<link rel="shortcut icon" href="/assets/soundrock/favicon.ico" />
<link rel="rockit-touch-icon" href="/assets/soundrock/rockit-touch-icon.png" />
<link rel="rockit-touch-icon" sizes="72x72" href="/assets/soundrock/rockit-touch-icon-72x72.png" />
<link rel="rockit-touch-icon" sizes="114x114" href="/assets/soundrock/rockit-touch-icon-114x114.png" />
<!--// Javascript //-->
<%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>

<!-- Outer Wrapper Start -->
<div id="outer-wrapper">
	<!-- Header Start -->
	<div id="header">
    	<div class="inner">
        	<!-- Container Start -->
            <div class="container">
                <!-- Logo Start -->
                <div class="five columns left">
                    <a href="index.html" class="logo"><img src="/assets/soundrock/logo.png" alt="" /></a>
                </div>
                <!-- Logo End -->
                <div class="eleven columns right">
                    <!-- Top Links Start -->
                    <ul class="top-links">
                        <li>
                            <h4 class="colr">Search Music</h4>
                            <div id="search-box">
                                <input name="" value="Enter any keyword"
                                onfocus="if(this.value=='Enter any keyword') {this.value='';}"
                                onblur="if(this.value=='') {this.value='Enter any keyword';}" type="text" class="bar" />
                                <button>Search</button>
                            </div>
                        </li>
                        <li>
                            <a href="<%= backend_index_path %>" class="colr">LOG IN</a>
                        </li>
                    </ul>
                    <!-- Top Links End -->
                </div>
                <%= render partial: "partials/menu" %>
            </div>
            <!-- Container End -->
        </div>
    </div>
    <!-- Header End -->
    <div class="clear"></div>

    <!-- Banner Start -->
    <%= yield :banner %>
    <!-- Banner End -->

    <!-- Content Section Start -->
    <%= yield %>
    <!-- Content Section End -->
    <div class="clear"></div>

    <!-- Footer Start -->
    <div id="footer">
    	<div class="inner">
        	<!-- // Go to Top // -->
        	<a href="#top" class="gotop">&nbsp;</a>
        	<!-- Footer Left Start -->
            <div class="ft-left">
            	<h4><a href="#" class="colr"><%= @settings.site_name %></a></h4>
                <ul class="links">
                	<li><a href="/">HOME</a></li>
                    <li><a href="<%= releases_path %>">RELEASES</a></li>
                    <li><a href="<%= artists_path %>">ARTISTS</a></li>
                    <li><a href="<%= about_path %>">ABOUT US</a></li>
                    <li><a href="<%= contact_path %>">CONTACT US</a></li>
                </ul>
                <ul class="social">
                	<li><a href="#" class="so-fb">&nbsp;</a></li>
                    <li><a href="#" class="so-twitter">&nbsp;</a></li>
                    <li><a href="#" class="so-vimeo">&nbsp;</a></li>
                </ul>
            </div>
            <!-- Footer Left End -->
            <!-- Footer Right Start -->
            <div class="ft-right">
            	<div class="contact-us">
                    <h4 class="colr">Contact Us</h4>
                    <p>For support, questions or feedback, mail us at </p>
                    <h4 class="white">Phone: <%= @settings.contact_phone %><br /><%= mail_to @settings.contact_email %></h4>
                </div>
            </div>
            <!-- Footer Left End -->
            <!-- Copyrights Start -->
            <div class="copyrights">
            	 © Copyright <a href="http://cantierecreativo.net/">CantiereCreativo</a> 2012
            </div>
            <!-- Copyrights End -->
            <div class="clear"></div>
        </div>
    </div>
    <!-- Footer End -->
    <div class="clear"></div>
</div>
<!-- Outer Wrapper End -->
</body>
</html>

app/views/pages/home.html.erb
<% content_for :banner do %>
    <div id="banner">
    	<div class="banner-in">
        	<div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
                	<a href="#"><img src="/assets/soundrock/banner1.jpg" title="#banner1" alt="" /></a>
                    <a href="#"><img src="/assets/soundrock/banner2.jpg" title="#banner2" alt="" /></a>
                    <a href="#"><img src="/assets/soundrock/banner3.jpg" title="#banner3" alt="" /></a>
                    <a href="#"><img src="/assets/soundrock/banner4.jpg" title="#banner4" alt="" /></a>
                </div>
                <!-- Banner Caption Start -->
                <div id="banner1" class="nivo-html-caption">
                  <%= @settings.home_banner_text.html_safe %>
                </div>
                <!-- Banner Caption End -->
                <!-- Banner Caption Start -->
                <div id="banner2" class="nivo-html-caption">
                  <%= @settings.home_banner_text.html_safe %>
                </div>
                <!-- Banner Caption End -->
                <!-- Banner Caption Start -->
                <div id="banner3" class="nivo-html-caption">
                  <%= @settings.home_banner_text.html_safe %>
                </div>
                <!-- Banner Caption End -->
                <!-- Banner Caption Start -->
                <div id="banner4" class="nivo-html-caption">
                  <%= @settings.home_banner_text.html_safe %>
                </div>
                <!-- Banner Caption End -->
            </div>
        </div>
    </div>
<% end %>

    <div id="content-sec">
    	<div class="inner">
        	<!-- Albums Start -->
        	<div class="albums">
            	<div id="albums">
                	<!-- About Albums Start -->
                    <div class="about-albums">
                      <%= @settings.home_text.html_safe %>

                        <!-- Albums Scroll Start -->
                        <div id="mcs5_container">
                            <div class="customScrollBox">
                                <div class="horWrapper"> 
                                    <div class="container">
                                        <div class="content">
                                            <ul>
                                              <% Release.all.each do |release| %>
                                                <% next unless release.artwork %>
                                                <li>
                                                  <%= link_to image_tag(release.artwork.image.thumb('80x84#').url), release_path(release) %>
                                                </li>
                                              <% end %>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="dragger_container">
                                        <div class="dragger"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Albums Scroll End -->
                    </div>
                    <!-- About Albums End -->
                    <!-- Now Playing Start -->
                    <div class="nowplaying">
                        <h1 class="heading colr">Now Playing</h1>
                        <div id="jquery_jplayer_2" class="jp-jplayer"></div>
                        <div id="jp_container_2" class="jp-audio">
                            <div class="jp-type-playlist">
                                <div class="jp-gui jp-interface">
                                    <ul class="jp-controls">
                                        <li><a href="javascript:;" class="jp-previous" tabindex="1">previous</a></li>
                                        <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                                        <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                                        <li><a href="javascript:;" class="jp-next" tabindex="1">next</a></li>
                                        <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                                        <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                                        <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                                        <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                                    </ul>
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-volume-bar">
                                        <div class="jp-volume-bar-value"></div>
                                    </div>
                                    <div class="jp-current-time"></div>
                                    <div class="jp-duration"></div>
                                    <ul class="jp-toggles">
                                        <li><a href="javascript:;" class="jp-shuffle" tabindex="1" title="shuffle">shuffle</a></li>
                                        <li><a href="javascript:;" class="jp-shuffle-off" tabindex="1" title="shuffle off">shuffle off</a></li>
                                        <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                                        <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                                    </ul>
                                </div>
                                <div class="jp-playlist">
                                    <div class="content">
                                        <ul>
                                            <li></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="jp-no-solution">
                                    <span>Update Required</span>
                                    To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Now Playing End -->
                </div>
                <a href="#" class="togglebtn">&nbsp;</a>
            </div>
            <!-- Albums End -->
            <!-- Columns Section Start -->
            <div class="columns-sec shade">
            	<div class="threecol">
            	<!-- Column One Start -->
                <div class="col1">
                    <!-- Twitter feeds Start -->
                    <div class="widget tweets noback">
                    	<h1 class="heading colr">From Twitter</h1>
                        <ul>
                        	<li>
                            	<div class="title">
                                	<a href="#" class="txthover">User 345 said</a>
                                    3 mins ago
                                </div>
                                <p>
                                	Esse molestie consequat vel illum dolore eu feugiat bit.ly/45rdf4 at. Nunc putamus parum claram anteposuerit #twitter #feed
                                </p>
                            </li>
                            <li>
                            	<div class="title">
                                	<a href="#" class="txthover">User 345 said</a>
                                    3 mins ago
                                </div>
                                <p>
                                	Esse molestie consequat vel illum dolore eu feugiat bit.ly/45rdf4 at. Nunc putamus parum claram anteposuerit #twitter #feed
                                </p>
                            </li>
                            <li>
                            	<div class="title">
                                	<a href="#" class="txthover">User 345 said</a>
                                    3 mins ago
                                </div>
                                <p>
                                	Esse molestie consequat vel illum dolore eu feugiat bit.ly/45rdf4 at. Nunc putamus parum claram anteposuerit #twitter #feed
                                </p>
                            </li>
                        </ul>
                        <a href="#" class="buttonone">Follow Us on Twitter</a>
                    </div>
                    <!-- Twitter feeds End -->
                </div>
                <!-- Column One End -->
                <!-- Column Two Start -->
                <div class="col2">
                    <!-- Latest News Start -->
                    <div class="latest-news noback">
                    	<h1 class="heading colr">Latest releases</h1>
                        <ul class="news-list">
                          <% @latest_releases.each do |release| %>
                        	<li>
                            	<div class="thumb">                                
                                	<a href="<%= release_path(release) %>">
                                    <%= image_tag(release.artwork.image.thumb('120x104#').url) if release.artwork %>
                                    <span>VEIW</span>
                                  </a>
                                </div>
                                <div class="desc">
                                	<h4><%= link_to release.name, release_path(release), class: "white" %></h4>
                                    <p class="post-opts"><%= artists_links release.artists %></p>
                                    <p><%= release.genres %><br /></p>
                                </div>
                            </li>
                            <% end %>
                        </ul>
                        <a href="<%= releases_path %>" class="buttonone">View All Releases</a>
                    </div>
                    <!-- Latest News End -->
                </div>
                <!-- Column Two End -->
                <!-- Column One Start -->
                <div class="col1 hidemobile">
                    <!-- Facebook Start -->
                    <div class="widget facebook">
                        <a href="#"><img src="/assets/soundrock/facebook.jpg" alt="" /></a>
                    </div>
                    <!-- Facebook End -->
                    <!-- Newsletter Start -->
                    <div class="widget newsletter noback">
                    	<h1 class="heading colr">Weekly Newsletter</h1>
                        <input type="text" value="Enter your valid email address" />
                        <button>SUBMIT</button>
                    </div>
                    <!-- Newsletter End -->
                </div>
                <!-- Column One End -->
                </div>
            </div>
            <!-- Columns Section End -->
        </div>
    </div>

app/views/partials/_menu.html.erb
                <!-- Navigation Start -->
                <div class="navigation">
                	<div id="smoothmenu1" class="ddsmoothmenu">
                    	<ul id="nav">
                        	<li class="<%= 'current-menu-item' if action_name == 'home' %>"><a href="/">Home</a></li>
                          <li class="<%= 'current-menu-item' if controller_name == 'releases' %>">
                              <a href="<%= releases_path %>">Releases</a>
                            	<ul>
                                <% ReleaseType.all.each do |type| %>
                                  <li><%= link_to type.name, type_releases_path(type: type.name.urlify) %></li>
                                <% end %>
                              </ul>
                          </li>
                          <li class="<%= 'current-menu-item' if controller_name == 'artists' %>"><a href="<%= artists_path %>">Artists</a></li>
                          <li class="<%= 'current-menu-item' if action_name == 'about' %>"><a href="<%= about_path %>">About Us</a></li>
                          <li class="<%= 'current-menu-item' if action_name == 'contact' %>"><a href="<%= contact_path %>">Contact Us</a></li>
                        </ul>
                        <div class="clear"></div>
                    </div>
                </div>
                <!-- Navigation End -->
                <div class="clear"></div>

app/views/releases/index.html.erb
<% content_for :banner do %>
    <div id="sub-banner">
    	<div class="in">
        	<a href="#"><img src="/assets/soundrock/sub-banner1.jpg" alt="" /></a>
        </div>
    </div>
<% end %>

    <!-- Album Shades Start -->
    <div id="album-shelves">
    	<h1 class="heading colr"><%= @title %></h1>
      <h2 class="heading" style="color:white"><%= "No releases found!" if @items.empty? %></h2>
    	<div class="inner">
        	<!-- Columns Section Start -->
            <ul class="album-list">
              <% @items.each do |release| %>
              	<li>
                <%= link_to image_tag(release.artwork.image.thumb('210x210#').url), release_path(release), class: "thumb" if release.artwork %>
                <h3><%= link_to release.name, release_path(release), class: "colr" %></h3>
                <h4><%= artists_links release.artists %></h4>
                    <p>
                    	<%= "Type: #{release.release_type.name}" if release.release_type %><br />
                      <%= "Genre: #{release.genres}" %><br />
                    </p>
                    <%= link_to "VIEW DETAIL", release_path(release), class: "bigbutton" %>
                </li>
                <% end %>
            </ul>
            <div class="clear"></div>
            <!-- Columns Section End -->
        </div>
    </div>
    <!-- Album Shades End -->